using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace api.Migrations
{
    /// <summary>
    /// The claim that stops two workers sending the same record to Foodspace (see api.Services.Foodspace.ForwardingClaim):
    /// who holds the record and until when. Nullable and additive, so the previous version of the API keeps working against
    /// this schema while a deployment rolls over. Generated by EF, then trimmed to the repo's hand-written style (no
    /// Designer file); AppDbContextModelSnapshot already reflects it.
    /// </summary>
    [DbContext(typeof(api.Data.AppDbContext))]
    [Migration("20261003143826_AddForwardingClaim")]
    public partial class AddForwardingClaim : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "forward_claim_id",
                table: "vetting_decisions",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "forward_claimed_until",
                table: "vetting_decisions",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "forward_claim_id",
                table: "cbo_collections",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "forward_claimed_until",
                table: "cbo_collections",
                type: "timestamp with time zone",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "forward_claim_id",
                table: "vetting_decisions");

            migrationBuilder.DropColumn(
                name: "forward_claimed_until",
                table: "vetting_decisions");

            migrationBuilder.DropColumn(
                name: "forward_claim_id",
                table: "cbo_collections");

            migrationBuilder.DropColumn(
                name: "forward_claimed_until",
                table: "cbo_collections");
        }
    }
}
