using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace api.Migrations
{
    /// <summary>
    /// Account management: the per-user security stamp that lets deactivating a user, resetting a password or changing a role end
    /// existing sessions (api.Infrastructure.TokenAccountCheck), and the append-only "user_audit" trail of account changes.
    /// Existing users get the all-zero stamp; their next sign-in issues tokens carrying it, so nothing is signed out by this
    /// migration except tokens issued before the stamp existed. Additive, so the previous version of the API keeps working
    /// against it while a deployment rolls over. Generated by EF, then trimmed to the repo's hand-written style (no Designer
    /// file); AppDbContextModelSnapshot already reflects it.
    /// </summary>
    [DbContext(typeof(api.Data.AppDbContext))]
    [Migration("20261003153525_AddUserSecurityStampAndAudit")]
    public partial class AddUserSecurityStampAndAudit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "security_stamp",
                table: "users",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateTable(
                name: "user_audit",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    occurred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    actor = table.Column<string>(type: "text", nullable: false),
                    action = table.Column<string>(type: "text", nullable: false),
                    target_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_username = table.Column<string>(type: "text", nullable: false),
                    detail = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user_audit", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_user_audit_target_user_id",
                table: "user_audit",
                column: "target_user_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "user_audit");

            migrationBuilder.DropColumn(
                name: "security_stamp",
                table: "users");
        }
    }
}
