// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.AdminAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PreviousAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("previous_attempts");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_status");

                    b.HasKey("Id")
                        .HasName("pk_admin_actions");

                    b.HasIndex("Form", "RecordId")
                        .HasDatabaseName("ix_admin_actions_form_record_id");

                    b.ToTable("admin_actions", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CboId")
                        .HasColumnType("text")
                        .HasColumnName("cbo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("api.Models.Cbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tone");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cbos");

                    b.ToTable("cbos", (string)null);
                });

            modelBuilder.Entity("api.Models.CboCollection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("CboId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cbo_id");

                    b.Property<bool>("CboSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("cbo_signed");

                    b.Property<string>("CollectNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collect_notes");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_note");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donor_name");

                    b.Property<bool>("DonorSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("donor_signed");

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_attempt_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool>("NoteAttached")
                        .HasColumnType("boolean")
                        .HasColumnName("note_attached");

                    b.Property<string>("DuplicateKey")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_key");

                    b.Property<string>("DuplicateOfId")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_of_id");

                    b.Property<string>("ForwardingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forwarding_status");

                    b.Property<DateTimeOffset?>("NextForwardAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_forward_attempt_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<bool>>("Shots")
                        .IsRequired()
                        .HasColumnType("boolean[]")
                        .HasColumnName("shots");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text")
                        .HasColumnName("submitted_by");

                    b.Property<int>("SyncAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("sync_attempts");

                    b.Property<string>("SyncError")
                        .HasColumnType("text")
                        .HasColumnName("sync_error");

                    b.Property<string>("SyncErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("sync_error_code");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cbo_collections");

                    b.HasIndex("CboId")
                        .HasDatabaseName("ix_cbo_collections_cbo_id");

                    b.HasIndex("SyncStatus")
                        .HasDatabaseName("ix_cbo_collections_sync_status");

                    b.HasIndex("ForwardingStatus")
                        .HasDatabaseName("ix_cbo_collections_forwarding_status");

                    b.HasIndex("DuplicateKey")
                        .IsUnique()
                        .HasDatabaseName("ux_cbo_collections_duplicate_key_original")
                        .HasFilter("duplicate_of_id IS NULL");

                    b.HasIndex("DuplicateOfId")
                        .HasDatabaseName("ix_cbo_collections_duplicate_of_id");

                    b.ToTable("cbo_collections", (string)null);
                });

            modelBuilder.Entity("api.Models.FoodspaceBeneficiaryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AccessToWater")
                        .HasColumnType("boolean")
                        .HasColumnName("access_to_water");

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("text")
                        .HasColumnName("additional_comments");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("address2");

                    b.Property<int>("AfricanServed")
                        .HasColumnType("integer")
                        .HasColumnName("african_served");

                    b.PrimitiveCollection<List<string>>("AgeGroups")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("age_groups");

                    b.Property<string>("Certificates")
                        .HasColumnType("text")
                        .HasColumnName("certificates");

                    b.Property<int>("ColouredServed")
                        .HasColumnType("integer")
                        .HasColumnName("coloured_served");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CoreBusiness")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("core_business");

                    b.PrimitiveCollection<List<string>>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("days_of_week");

                    b.Property<string>("DigitalCapabilities")
                        .HasColumnType("text")
                        .HasColumnName("digital_capabilities");

                    b.Property<string>("DistributionChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distribution_channel");

                    b.Property<bool>("EaseOfAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("ease_of_access");

                    b.Property<string>("FacilityPhotos")
                        .HasColumnType("text")
                        .HasColumnName("facility_photos");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feeding_frequency");

                    b.Property<int>("FemalesServed")
                        .HasColumnType("integer")
                        .HasColumnName("females_served");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("FoodStorage")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("food_storage");

                    b.Property<int>("FullTimeFemales")
                        .HasColumnType("integer")
                        .HasColumnName("full_time_females");

                    b.Property<int>("FullTimeMales")
                        .HasColumnType("integer")
                        .HasColumnName("full_time_males");

                    b.PrimitiveCollection<List<string>>("Gender")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("gender");

                    b.Property<bool>("HasConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("has_consent");

                    b.Property<bool>("HasPolicy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_policy");

                    b.Property<bool>("HasSla")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sla");

                    b.Property<int>("IndianServed")
                        .HasColumnType("integer")
                        .HasColumnName("indian_served");

                    b.PrimitiveCollection<List<string>>("InfrastructureChecks")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("infrastructure_checks");

                    b.Property<bool>("KitchenCleanliness")
                        .HasColumnType("boolean")
                        .HasColumnName("kitchen_cleanliness");

                    b.Property<string>("KitchenImages")
                        .HasColumnType("text")
                        .HasColumnName("kitchen_images");

                    b.Property<long?>("LastDateFed")
                        .HasColumnType("bigint")
                        .HasColumnName("last_date_fed");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<int>("MalesServed")
                        .HasColumnType("integer")
                        .HasColumnName("males_served");

                    b.PrimitiveCollection<List<string>>("MealsProvided")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meals_provided");

                    b.Property<string>("NpoCertificate")
                        .HasColumnType("text")
                        .HasColumnName("npo_certificate");

                    b.Property<bool>("ParkingSecurity")
                        .HasColumnType("boolean")
                        .HasColumnName("parking_security");

                    b.Property<string>("PboCertificate")
                        .HasColumnType("text")
                        .HasColumnName("pbo_certificate");

                    b.Property<bool>("PestFree")
                        .HasColumnType("boolean")
                        .HasColumnName("pest_free");

                    b.Property<string>("PoliceProximity")
                        .HasColumnType("text")
                        .HasColumnName("police_proximity");

                    b.Property<string>("Programmes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("programmes");

                    b.Property<string>("ProposalWriting")
                        .HasColumnType("text")
                        .HasColumnName("proposal_writing");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.PrimitiveCollection<List<string>>("Race")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("race");

                    b.Property<bool>("RegisteredDsd")
                        .HasColumnType("boolean")
                        .HasColumnName("registered_dsd");

                    b.Property<bool>("RegisteredNpo")
                        .HasColumnType("boolean")
                        .HasColumnName("registered_npo");

                    b.Property<string>("RelianceOnSaHarvest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reliance_on_sa_harvest");

                    b.PrimitiveCollection<List<string>>("TargetPopulation")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("target_population");

                    b.Property<bool>("Toilets")
                        .HasColumnType("boolean")
                        .HasColumnName("toilets");

                    b.Property<int>("TotalServed")
                        .HasColumnType("integer")
                        .HasColumnName("total_served");

                    b.Property<string>("TransportCapacity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_capacity");

                    b.Property<int>("Volunteers")
                        .HasColumnType("integer")
                        .HasColumnName("volunteers");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.Property<string>("What3words")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("what3words");

                    b.Property<int>("WhiteServed")
                        .HasColumnType("integer")
                        .HasColumnName("white_served");

                    b.HasKey("Id")
                        .HasName("pk_foodspace_beneficiary_records");

                    b.ToTable("foodspace_beneficiary_records", (string)null);
                });

            modelBuilder.Entity("api.Models.ProductLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Kg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_lines");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_product_lines_collection_id");

                    b.ToTable("product_lines", (string)null);
                });

            modelBuilder.Entity("api.Models.VettingDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long>("DecisionTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("decision_timestamp");

                    b.Property<string>("FoodspaceRecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("foodspace_record_id");

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_attempt_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("officer_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ForwardingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forwarding_status");

                    b.Property<DateTimeOffset?>("NextForwardAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_forward_attempt_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("SyncAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("sync_attempts");

                    b.Property<string>("SyncError")
                        .HasColumnType("text")
                        .HasColumnName("sync_error");

                    b.Property<string>("SyncErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("sync_error_code");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vetting_decisions");

                    b.HasIndex("FoodspaceRecordId")
                        .HasDatabaseName("ix_vetting_decisions_foodspace_record_id");

                    b.HasIndex("OfficerId")
                        .HasDatabaseName("ix_vetting_decisions_officer_id");

                    b.HasIndex("SyncStatus")
                        .HasDatabaseName("ix_vetting_decisions_sync_status");

                    b.ToTable("vetting_decisions", (string)null);
                });

            modelBuilder.Entity("api.Models.ProductLine", b =>
                {
                    b.HasOne("api.Models.CboCollection", "Collection")
                        .WithMany("ProductLines")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_lines_cbo_collections_collection_id");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("api.Models.CboCollection", b =>
                {
                    b.Navigation("ProductLines");
                });
#pragma warning restore 612, 618
        }
    }
}
